In [1]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [2]:
share_living_space = apartment[1]/apartment[0]

In [3]:
apartment = np.delete(apartment, [0, 1])

In [4]:
apartment = np.append(apartment, share_living_space)

In [5]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [6]:
share_living_space

0.5277310924369748

In [7]:
len(apartment)

5

In [10]:
a = np.array([2,3,2.5], float)
a = a*72
b = np.array([120,150,90], float)
c = np.array([130,130,130], float)
a+b+c

array([394., 496., 400.])

In [11]:
p=np.array([2,4,5])
v=np.array([8,10,2])
s=np.array([0,12,7])
500*p+100*v+0*s

array([1800, 3000, 2700])

In [12]:
a1=np.array([4,5])
b1=np.array([2,1])
c1=np.array([1,0])
2*a1+(-3*b1)+5*c1

array([7, 7])

In [16]:
r1=np.array([3,4,5,9])
r2=np.array([1,5,3,6])
400*r2-200*r1

array([-200, 1200,  200,  600])

In [18]:
s1=np.array([4,5,-1])
s2=np.array([2,0,1])
np.dot(s1,s2)

7

In [31]:
l1=np.array([4,6,1])
l2=l1*l1
np.sqrt(l2.sum())

7.280109889280518

In [37]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
vec = Hut_Paradise_DF.values
vec

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [36]:
vec[4]

array([40, 33,  1,  6, 20, 16])

In [38]:
vec[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [42]:
vec[2:3,3]

array([10])

In [44]:
len(vec)

9

In [47]:
obsh = vec[:, 1]
jil = vec[:, 5]
obsh, jil

(array([50, 52, 80, 33, 33, 44, 80, 65, 65]),
 array([37, 40, 65, 20, 16, 35, 60, 50, 40]))

In [48]:
obsh-jil

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [49]:
cost = vec[:,0]
cost

array([ 65,  70, 120,  35,  40,  50, 100,  90,  85])

In [53]:
grvn = 10/4
cost/grvn

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [55]:
look=np.array([10,20,30,15,5,40,20,8,20])
look

array([10, 20, 30, 15,  5, 40, 20,  8, 20])

In [62]:
demos = vec[:, 4]
demos

array([ 8,  4,  5, 10, 20, 12,  5,  1, 10])

In [64]:
(look*demos).sum()

1348

In [65]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [67]:
u@v, u@w, v@w

(0, 0, 0)

<img src="math_pic0.png"></img>

In [69]:
nev=2*v+(-3*w)
nev

array([-3, 14,  3,  4,  2])

In [70]:
u@nev

0

In [73]:
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)
u_norm,v_norm,w_norm

(array([0.8660254 , 0.        , 0.28867513, 0.28867513, 0.28867513]),
 array([ 0.        ,  0.33333333,  0.        ,  0.66666667, -0.66666667]),
 array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143]))

In [74]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [76]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
Inc

array([[100, 220, 140],
       [150, 200, 130],
       [ 90,  80, 100]])

In [77]:
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption])
Cons

array([[ 50,  50,  60],
       [100,  80, 140],
       [100,  20, 140]])

In [80]:
net = Inc-(Inc*0.13)
net

array([[ 87. , 191.4, 121.8],
       [130.5, 174. , 113.1],
       [ 78.3,  69.6,  87. ]])

In [81]:
prof = net - Cons
prof 

array([[ 37. , 141.4,  61.8],
       [ 30.5,  94. , -26.9],
       [-21.7,  49.6, -53. ]])

In [85]:
matr = np.array([[1,1],[2,-1],[1,2]])
tmatr = matr.T
matr, tmatr

(array([[ 1,  1],
        [ 2, -1],
        [ 1,  2]]),
 array([[ 1,  2,  1],
        [ 1, -1,  2]]))

In [91]:
matr@tmatr

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [93]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A, x

(array([[ 5, -1,  3,  1,  2],
        [-2,  8,  5, -1,  1]]),
 array([1, 2, 3, 4, 5]))

In [96]:
A@x

array([26, 30])

In [97]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )
A, B

(array([[1, 9, 8, 5],
        [3, 6, 3, 2],
        [3, 3, 3, 3],
        [0, 2, 5, 9],
        [4, 4, 1, 2]]),
 array([[ 1, -1,  0,  1,  1],
        [-2,  0,  2, -1,  1]]))

In [99]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [100]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
x,y,z

(array([1, 2, 1, 0, 4]),
 array([ 2,  1, -1,  1,  0]),
 array([-1,  1, -1,  0,  0]))

In [102]:
A=np.matrix([[1,2,1,0,4],[ 2,1,-1,1,0],[-1,1,-1,0,0]])
A, A.T

(matrix([[ 1,  2,  1,  0,  4],
         [ 2,  1, -1,  1,  0],
         [-1,  1, -1,  0,  0]]),
 matrix([[ 1,  2, -1],
         [ 2,  1,  1],
         [ 1, -1, -1],
         [ 0,  1,  0],
         [ 4,  0,  0]]))

In [105]:
A@A.T

matrix([[22,  3,  0],
        [ 3,  7,  0],
        [ 0,  0,  3]])

In [106]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                         'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                         'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                         'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                         'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                        }, 
                        index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                         'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                         'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                         'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                         'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                        }, 
                        index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [107]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [108]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [115]:
Profit_DF=Price_DF*Count_DF
Profit_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               20.0              7.5         12.0     12.0  10.0
Борис              3.6             52.5          3.0     25.0   6.0
Вика              24.0             24.0          0.0     15.0   8.0
Галя               7.2              9.6         50.4     11.2  10.0
Дима              15.0             87.5         54.0     25.0  27.0
Егор              50.0             15.0          6.0     34.0  30.0
Женя              24.2              1.0          6.0     12.5  34.0
Юра               31.5              0.0         77.5     31.0  56.0

In [116]:
Profit_DF.values[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [117]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [126]:
SaloonCom_DF = Profit_DF@com
SaloonCom_DF.values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [160]:
Profit_DF.sum(axis=1).values-SaloonCom_DF.values

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [161]:
A = np.matrix([[1,2],[2,5]])
A

matrix([[1, 2],
        [2, 5]])

In [163]:
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [164]:
A=np.matrix([[1,2],[1,1]])
B=np.matrix([[5,-2],[-1,4]])
A,B

(matrix([[1, 2],
         [1, 1]]),
 matrix([[ 5, -2],
         [-1,  4]]))

In [165]:
A+B

matrix([[6, 0],
        [0, 5]])

In [166]:
A=np.matrix([[2,0,0],[0,1,0],[0,0,4]])
A

matrix([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]])

In [167]:
np.linalg.det(A)

7.999999999999998

In [171]:
A1 = np.linalg.inv(A)
np.linalg.det(A1)

0.12500000000000003

In [176]:
A = np.matrix([[1,0,3,5],[0,4,5,5],[0,0,0,0],[0,0,0,0]])
B = np.matrix([[1,0,3,5],[0,4,5,5],[0,0,0,4],[0,0,0,0]])
A, B

(matrix([[1, 0, 3, 5],
         [0, 4, 5, 5],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 0, 3, 5],
         [0, 4, 5, 5],
         [0, 0, 0, 4],
         [0, 0, 0, 0]]))

In [184]:
np.linalg.matrix_rank(A)

2

In [185]:
np.linalg.matrix_rank(B)

3

In [186]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [188]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [189]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [190]:
A = np.matrix([v1,v2,v3,v4])
A

matrix([[ 9, 10,  7,  7,  9],
        [ 2,  0,  5,  1,  4],
        [ 4,  0,  0,  4,  1],
        [ 3, -4,  3, -1, -4]])

In [191]:
np.linalg.matrix_rank(A)

4

In [193]:
A_GR = A@A.T
A_GR

matrix([[360,  96,  73, -35],
        [ 96,  46,  16,   4],
        [ 73,  16,  33,   4],
        [-35,   4,   4,  51]])

In [195]:
np.linalg.det(A_GR)

3716647.9999999995

In [196]:
np.linalg.inv(A_GR)

matrix([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
        [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
        [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
        [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [198]:
A = np.matrix([[-2,7],[3,5]])
np.linalg.det(A)

-31.0

In [200]:
B = np.matrix([[2,0,5],[1,3,16],[0,-1,10]])
np.linalg.det(B)

87.0

In [201]:
C = np.matrix([[2,-1],[-1,2]])
C

matrix([[ 2, -1],
        [-1,  2]])

In [204]:
A = np.matrix([[1,2,1],[2,5,6],[3,8,10]])
A

matrix([[ 1,  2,  1],
        [ 2,  5,  6],
        [ 3,  8, 10]])

In [205]:
np.linalg.det(A)

-0.9999999999999999

In [206]:
A1 = np.matrix([[3,2,1],[1,5,6],[1,8,10]])
A1

matrix([[ 3,  2,  1],
        [ 1,  5,  6],
        [ 1,  8, 10]])

In [207]:
np.linalg.det(A1)

0.9999999999999893

In [208]:
A2 = np.matrix([[1,3,1],[2,1,6],[3,1,10]])
A2

matrix([[ 1,  3,  1],
        [ 2,  1,  6],
        [ 3,  1, 10]])

In [209]:
np.linalg.det(A2)

-2.999999999999994

In [210]:
A3 = np.matrix([[1,2,3],[2,5,1],[3,8,1]])
A3

matrix([[1, 2, 3],
        [2, 5, 1],
        [3, 8, 1]])

In [211]:
np.linalg.det(A3)

1.999999999999998

In [212]:
A = np.matrix([[2,3,0],[3,4,0],[7,8,-4]])
A

matrix([[ 2,  3,  0],
        [ 3,  4,  0],
        [ 7,  8, -4]])

In [213]:
np.linalg.det(A)

4.0

In [215]:
B = np.matrix([[2,3,0,2,3],[3,4,0,3,4],[7,8,-4,7,8]])
B

matrix([[ 2,  3,  0,  2,  3],
        [ 3,  4,  0,  3,  4],
        [ 7,  8, -4,  7,  8]])

In [216]:
((2*4*-4)+(3*0*7)+(0*3*8))-((3*3*-4)+(2*0*8)+(0*4*7))

4

In [217]:
A = np.matrix([[4,7],[5,10]])
A

matrix([[ 4,  7],
        [ 5, 10]])

In [234]:
A1 = np.linalg.inv(A)
A1.T

matrix([[ 2. , -1. ],
        [-1.4,  0.8]])

In [220]:
V = np.array([20,30])
V

array([20, 30])

In [233]:
V*A1.T

matrix([[-2.,  4.]])

In [275]:
A = np.matrix([[1,5],[2,1],[1,1]])
A, A.T

(matrix([[1, 5],
         [2, 1],
         [1, 1]]),
 matrix([[1, 2, 1],
         [5, 1, 1]]))

In [277]:
w = np.matrix([[1,1]])
w

matrix([[1, 1]])

In [267]:
b = w*A.T
b

matrix([[6, 3, 2]])

In [265]:
b1 = np.matrix([[1,2,2]])
b1

matrix([[1, 2, 2]])

In [281]:
b1-b, b-b1

(matrix([[-5, -1,  0]]), matrix([[5, 1, 0]]))

matrix([[-5],
        [-1],
        [ 0]])