In [29]:
import numpy as np

In [30]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [31]:
A

array([[ 6,  8,  6],
       [11,  6,  5],
       [ 8, 10,  6]])

In [32]:
B

array([[ 0,  1,  0],
       [ 2,  0, -1],
       [ 1,  0,  0]])

In [33]:
# Поэлементное умножение
A*B

array([[ 0,  8,  0],
       [22,  0, -5],
       [ 8,  0,  0]])

In [34]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 22   6  -8]
 [ 17  11  -6]
 [ 26   8 -10]]


In [35]:
# Матричное умножение
np.dot(A,B)

array([[ 22,   6,  -8],
       [ 17,  11,  -6],
       [ 26,   8, -10]])

In [36]:
# Матричное умножение
A@B

array([[ 22,   6,  -8],
       [ 17,  11,  -6],
       [ 26,   8, -10]])

In [37]:
# Порядок умножения AB != BA
B@A

array([[11,  6,  5],
       [ 4,  6,  6],
       [ 6,  8,  6]])

In [38]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[10  9  7  7  7]
 [ 7  5 10  9  5]
 [ 8  8 10 10 11]]
B:
 [[ 0  2]
 [-1  3]
 [ 1 -2]
 [ 0  0]
 [ 3  1]]


In [39]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[19, 40],
       [20, 14],
       [35, 31]])

In [40]:
# Умножение прямоугольных матриц возможно не в любом порядке
# B@A

In [41]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [42]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-3  0 -2  0]
 [-3  3  1  3]
 [ 3  2 -1  0]
 [ 1  1 -4  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-3  0  0  0]
 [-3  6  0 -3]
 [ 3  4  0  0]
 [ 1  2  0 -1]]
DA:
 [[-3  0 -2  0]
 [-6  6  2  6]
 [ 0  0  0  0]
 [-1 -1  4 -1]]


In [43]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [44]:
# b@A

In [45]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [46]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [47]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [48]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [49]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])