In [5]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [6]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [7]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [18]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[8, 2, 0],
       [3, 5, 7],
       [9, 1, 1]])

In [9]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [11]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.randint(0, 5, (3, 3))

array([[1, 3, 0],
       [3, 1, 3],
       [1, 3, 1]])

In [16]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.zeros((10, 7)), np.ones((3,3,3))

(array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]),
 array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]))

In [19]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [24]:
my_array = np.array([x for x in range(10)])
my_array[5],\
my_array[-1],\
my_array[3:6],\
my_array[1:8:3],\

(5, 9, array([3, 4, 5]), array([1, 4, 7]))

In [33]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2],\
my_array[1,2],\
my_array[1],\
my_array[:,2],\
my_array[1:,1:3]

(12,
 12,
 array([10, 11, 12, 13]),
 array([ 3, 12, 47]),
 array([[11, 12],
        [46, 47]]))

In [34]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [36]:
sum(big_secret[:,-1])

3154.332495807108

In [52]:
a = big_secret[:,0:5]
b = np.asarray(a)
np.trace(b)

2248955.5378441787

In [64]:
a = big_secret[:,-5:]
a, a.diagonal(), a.diagonal().prod()

(array([[ 460.        ,  276.        ,  686.        ,  490.        ,
          294.        ],
        [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
           33.1662479 ],
        [2116.        , 2209.        , 2304.        , 2401.        ,
         2500.        ],
        [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
           33.1662479 ],
        [ 460.        ,  276.        ,  686.        ,  490.        ,
          294.        ]]),
 array([ 460.        ,   33.07567082, 2304.        ,   33.13608305,
         294.        ]),
 341505315559.2347)

In [67]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[88, 84, 38, 17, 86, 93],
       [ 3, 58, 40, 33, 23, 64],
       [17,  3, 15, 59,  5, 26],
       [33,  6, 75, 48, 97, 96]])

In [69]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[40, 33],
       [15, 59]])

In [71]:
my_slice[:] = 0
my_array

array([[88, 84, 38, 17, 86, 93],
       [ 3, 58,  0,  0, 23, 64],
       [17,  3,  0,  0,  5, 26],
       [33,  6, 75, 48, 97, 96]])

In [83]:
[idx for idx, x in np.ndenumerate(big_secret) if idx[0]%2 == 0 and idx[1]%2 == 0]

[(0, 0),
 (0, 2),
 (0, 4),
 (0, 6),
 (0, 8),
 (0, 10),
 (0, 12),
 (0, 14),
 (0, 16),
 (0, 18),
 (0, 20),
 (0, 22),
 (0, 24),
 (0, 26),
 (0, 28),
 (0, 30),
 (0, 32),
 (0, 34),
 (0, 36),
 (0, 38),
 (0, 40),
 (0, 42),
 (0, 44),
 (0, 46),
 (0, 48),
 (0, 50),
 (2, 0),
 (2, 2),
 (2, 4),
 (2, 6),
 (2, 8),
 (2, 10),
 (2, 12),
 (2, 14),
 (2, 16),
 (2, 18),
 (2, 20),
 (2, 22),
 (2, 24),
 (2, 26),
 (2, 28),
 (2, 30),
 (2, 32),
 (2, 34),
 (2, 36),
 (2, 38),
 (2, 40),
 (2, 42),
 (2, 44),
 (2, 46),
 (2, 48),
 (2, 50),
 (4, 0),
 (4, 2),
 (4, 4),
 (4, 6),
 (4, 8),
 (4, 10),
 (4, 12),
 (4, 14),
 (4, 16),
 (4, 18),
 (4, 20),
 (4, 22),
 (4, 24),
 (4, 26),
 (4, 28),
 (4, 30),
 (4, 32),
 (4, 34),
 (4, 36),
 (4, 38),
 (4, 40),
 (4, 42),
 (4, 44),
 (4, 46),
 (4, 48),
 (4, 50)]

In [99]:
for i,x in enumerate(big_secret):
    for j,y in enumerate(x):
        if i%2==0 and j%2==0:
            big_secret[i][j] = -1
        else:
            big_secret[i][j] = 1
big_secret

array([[-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 

In [101]:
a = big_secret[:,-5:]
a.diagonal().sum()

-1.0

In [102]:
a.diagonal().prod()

-1.0

In [103]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [105]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [107]:
my_array = np.random.randint(0, 10, 20)
print(my_array)
my_array.reshape((4,5))

[0 6 7 0 5 4 5 9 0 5 8 7 1 3 3 4 0 0 7 8]


array([[0, 6, 7, 0, 5],
       [4, 5, 9, 0, 5],
       [8, 7, 1, 3, 3],
       [4, 0, 0, 7, 8]])

In [109]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
print(my_array)
my_array.flatten()

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [112]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[2, 1, 5, 7],
       [6, 3, 5, 1],
       [2, 4, 2, 1]])

In [114]:
my_array<5

array([[ True,  True, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [115]:
my_array[my_array<5]

array([2, 1, 3, 1, 2, 4, 2, 1])

In [116]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[2, 5],
       [6, 5],
       [2, 2]])

In [118]:
my_array = np.random.randint(0, 10, (4, 6))
print(my_array)
print(np.sort(my_array, axis=1))
print(np.sort(my_array, axis=0))

[[0 8 4 9 5 4]
 [8 2 6 8 3 0]
 [2 8 3 7 8 6]
 [4 4 7 1 4 0]]
[[0 4 4 5 8 9]
 [0 2 3 6 8 8]
 [2 3 6 7 8 8]
 [0 1 4 4 4 7]]
[[0 2 3 1 3 0]
 [2 4 4 7 4 0]
 [4 8 6 8 5 4]
 [8 8 7 9 8 6]]


In [123]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [131]:
np.cos(great_secret[0]).sum()

0.16006721889793019

In [133]:
np.sum(great_secret[great_secret>50])

5470.0

In [136]:
great_secret.flatten()[150]

7.0710678118654755

In [140]:
sorted = np.sort(great_secret, axis=0)
print(sorted)

[[ 0.          4.64158883 40.        ]
 [ 1.          4.65700951 40.4       ]
 [ 1.41421356  4.67232873 40.8       ]
 [ 1.73205081  4.68754815 41.2       ]
 [ 2.          4.70266938 41.6       ]
 [ 2.23606798  4.71769398 42.        ]
 [ 2.44948974  4.73262349 42.4       ]
 [ 2.64575131  4.7474594  42.8       ]
 [ 2.82842712  4.76220316 43.2       ]
 [ 3.          4.77685618 43.6       ]
 [ 3.16227766  4.79141986 44.        ]
 [ 3.31662479  4.80589553 44.4       ]
 [ 3.46410162  4.82028453 44.8       ]
 [ 3.60555128  4.83458813 45.2       ]
 [ 3.74165739  4.84880759 45.6       ]
 [ 3.87298335  4.86294413 46.        ]
 [ 4.          4.87699896 46.4       ]
 [ 4.12310563  4.89097325 46.8       ]
 [ 4.24264069  4.90486813 47.2       ]
 [ 4.35889894  4.91868473 47.6       ]
 [ 4.47213595  4.93242415 48.        ]
 [ 4.58257569  4.94608744 48.4       ]
 [ 4.69041576  4.95967566 48.8       ]
 [ 4.79583152  4.97318983 49.2       ]
 [ 4.89897949  4.98663095 49.6       ]
 [ 5.          5.        

In [144]:
np.sum(sorted[-1:])

115.12148016521353

<b>Среднее арифметическое (mean)</b> — сумма всех значений, делённая на их количество, показывает общую тенденцию данных и описывает их одним числом. Узнаем среднюю успеваемость школьников в классе, используя функцию mean:

<b>Медиана</b> — это такое число, что ровно половина элементов из выборки больше него, а другая половина меньше него. Если в выборке есть выбросы (значения, которые принимают величину существенно выше или ниже среднего и выделяются из всей выборки), то медиана будет лучше характеризовать всю выборку, чем среднее арифметическое.

<b>Корреляция</b> — статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

In [6]:
students = np.array([[1,135,34,4],[2,160,43,5],[3,163,40,4.3],[4,147,44,5],[5,138,41,4.7],[6,149,54,3.9],[7,136,39,4.2],[8,154,48,4.9],[9,137,35,3.7],[10,165,60,4.6]])
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [7]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [8]:
median = np.median(students[:,-1])
median

4.449999999999999

In [9]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [10]:
median = np.median(students[:,-2])
median

42.0

In [11]:
mean = np.mean(students[:,-2])
print(mean, mean-median)

43.8 1.7999999999999972


In [12]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [13]:
print(np.corrcoef(students[:,1], students[:,2]))
print(np.corrcoef(students[:,1], students[:,-1]))
print(np.corrcoef(students[:,2], students[:,-1]))

[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]


<b>Математическое ожидание</b> — среднее значение случайной величины при стремлении числа её измерений к бесконечности. Если число измерений конечно, то для оценки среднего значения величины используется среднее арифметическое.

<b>Дисперсия</b> - мера разброса случайной величины относительно её математического ожидания.

D\[X\]=M\[(X-M\[X\])^2\]

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/3a0e76f59a6caf64db3ec11d74cc4687281325ef)

Как следует из формулы, дисперсия случайной величины X равна математическому ожиданию квадрата отклонения случайной величины от ее математического ожидания. То есть, если величина дисперсии небольшая, значит, все числа в выборке имеют близкие друг к другу значения, а чем она больше — тем значительнее разброс показателей.

**Стандартное отклонение** — самый распространенный показатель рассеивания случайной величины относительно её математического ожидания.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/8c535aeb360aec0139028ee203973550bb364cbb)

Стандартное отклонение равно квадратному корню из дисперсии. Низкое стандартное отклонение показывает, что все значения в выборке сгруппированы около среднего значения.  Большой показатель этой величины говорит о том, что разброс значений большой. 

In [14]:
std = np.std(students[:,1])
std

11.083320801997928

In [15]:
std = np.std(students[:,-1])
std

0.4517742799230607

In [16]:
ptp = np.ptp(students[:,-2])
students[:,-2], ptp

(array([34., 43., 40., 44., 41., 54., 39., 48., 35., 60.]), 26.0)

In [17]:
results = students[:,-2]
results

array([34., 43., 40., 44., 41., 54., 39., 48., 35., 60.])

### Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

![dispersion](dispersion.png)

In [18]:
# calculate mean
m = sum(results) / len(results) 
# calculate variance using a list comprehension 
varRes = sum([(xi - m)**2 for xi in results]) / len(results)
varRes

60.36

<img src='./dispersion_1.png' width='700px'/>

In [39]:
import numpy as np
appl = [3, 5, 6, 4, 3, 5, 4]
oran = [1, 3, 7, 9, 2, 6, 2]
m = sum(appl) / len(appl)
n = sum(oran) / len(oran)
print((( sum([(a - m)**2 for a in appl])/(len(appl)-1))**0.5) / m)
print((( sum([(a - n)**2 for a in oran])/(len(oran)-1))**0.5) / m)

0.2596293654566205
0.7091988176547978


In [20]:
np.var(results) 

60.36

In [176]:
60.36**(1/2), np.std(results)

(7.769169839822013, 7.769169839822013)

In [177]:
np.array([x/x for x in range(1,10)]*5)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [178]:
np.ones((5,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [179]:
np.random.randint(1, 10, (10, 10))

array([[6, 4, 6, 4, 2, 6, 8, 8, 5, 3],
       [8, 7, 6, 7, 9, 6, 5, 6, 1, 3],
       [8, 3, 2, 5, 7, 5, 1, 5, 1, 5],
       [6, 4, 4, 7, 2, 8, 7, 3, 8, 3],
       [8, 3, 8, 8, 7, 6, 3, 5, 2, 6],
       [2, 6, 4, 8, 8, 4, 6, 6, 4, 1],
       [5, 1, 8, 2, 1, 6, 1, 9, 6, 1],
       [9, 4, 4, 6, 8, 9, 1, 1, 1, 3],
       [3, 5, 4, 4, 7, 9, 5, 9, 2, 1],
       [9, 4, 8, 3, 3, 6, 5, 4, 5, 1]])

In [181]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array[1:-1, 1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [182]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [183]:
my_sin = np.sin(my_array)
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [185]:
my_sin.sum()

-0.05812430261413373

In [186]:
my_sin[1:-1,1:-1] = 1
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [187]:
my_sin.sum()

7.571718421269144

In [196]:
new_sin = my_sin[:, :4].flatten().reshape((10,2))
new_sin

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [197]:
new_sin[:,0], new_sin[:,0].sum()

(array([ 0.84147098,  0.14112001, -0.2794155 ,  1.        , -0.99999021,
         1.        , -0.28790332,  1.        ,  0.83665564, -0.8462204 ]),
 2.4057172058139544)

In [203]:
bigdata = [x**2 for x in range(100, 1000) if x%2]
bigdata[:10]

[10201, 10609, 11025, 11449, 11881, 12321, 12769, 13225, 13689, 14161]

In [206]:
np.median(bigdata)

302501.0

In [207]:
np.std(bigdata)

292095.0301991155

In [224]:
bigdata[::2]

[10201,
 11025,
 11881,
 12769,
 13689,
 14641,
 15625,
 16641,
 17689,
 18769,
 19881,
 21025,
 22201,
 23409,
 24649,
 25921,
 27225,
 28561,
 29929,
 31329,
 32761,
 34225,
 35721,
 37249,
 38809,
 40401,
 42025,
 43681,
 45369,
 47089,
 48841,
 50625,
 52441,
 54289,
 56169,
 58081,
 60025,
 62001,
 64009,
 66049,
 68121,
 70225,
 72361,
 74529,
 76729,
 78961,
 81225,
 83521,
 85849,
 88209,
 90601,
 93025,
 95481,
 97969,
 100489,
 103041,
 105625,
 108241,
 110889,
 113569,
 116281,
 119025,
 121801,
 124609,
 127449,
 130321,
 133225,
 136161,
 139129,
 142129,
 145161,
 148225,
 151321,
 154449,
 157609,
 160801,
 164025,
 167281,
 170569,
 173889,
 177241,
 180625,
 184041,
 187489,
 190969,
 194481,
 198025,
 201601,
 205209,
 208849,
 212521,
 216225,
 219961,
 223729,
 227529,
 231361,
 235225,
 239121,
 243049,
 247009,
 251001,
 255025,
 259081,
 263169,
 267289,
 271441,
 275625,
 279841,
 284089,
 288369,
 292681,
 297025,
 301401,
 305809,
 310249,
 314721,
 319225,
 

In [225]:
corr = np.corrcoef(bigdata[::2], bigdata[1::2])
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])