In [2]:
import numpy as np

zer = np.zeros((2,5))
print(zer)
print(zer + 5)
print(zer.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
(2, 5)


In [3]:
matrix = np.random.random((3,3))
print(matrix)
matrix.sort()
print(matrix)

[[0.93845898 0.10896371 0.0356496 ]
 [0.47141991 0.36255477 0.26226085]
 [0.93390598 0.00286586 0.64633324]]
[[0.0356496  0.10896371 0.93845898]
 [0.26226085 0.36255477 0.47141991]
 [0.00286586 0.64633324 0.93390598]]


In [4]:
print(np.random.randint(1, 5, (3,4)))

[[1 4 3 4]
 [2 2 4 2]
 [1 1 1 4]]


In [5]:
x = np.linspace(0,4,10)
print(x)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [6]:
print(x.mean(), x.sum(), x.max())

2.0 20.0 4.0


In [7]:
x2 = np.reshape(x, (5, 2))
print(x2)
print(x2.shape)
print(x2.mean())
print(x2.sum())

[[0.         0.44444444]
 [0.88888889 1.33333333]
 [1.77777778 2.22222222]
 [2.66666667 3.11111111]
 [3.55555556 4.        ]]
(5, 2)
2.0
20.0


In [8]:
y = np.linspace(0,4,10).reshape(-1,1)
print(y)

[[0.        ]
 [0.44444444]
 [0.88888889]
 [1.33333333]
 [1.77777778]
 [2.22222222]
 [2.66666667]
 [3.11111111]
 [3.55555556]
 [4.        ]]


In [9]:
print(x @ y) # np.dot(x,y)
print((y**2).sum())

[56.2962963]
56.29629629629629


In [10]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 6 3 4 9 8 7 2 5 1]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 0 6]]


In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.copy()[:, ::-1]
print(A)
print(B)
B[1][1] = 0
print(A)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [13]:
x = np.random.random((2,4))
print(x)
print(x.T)

[[0.17679056 0.34176496 0.73446879 0.83385606]
 [0.98517836 0.9593545  0.46681618 0.26364513]]
[[0.17679056 0.98517836]
 [0.34176496 0.9593545 ]
 [0.73446879 0.46681618]
 [0.83385606 0.26364513]]


In [17]:
mt = np.random.random((3,10))
print(x)
print(x.T)
print(np.equal(x, x.T).all())

[[0.17679056 0.34176496 0.73446879 0.83385606]
 [0.98517836 0.9593545  0.46681618 0.26364513]]
[[0.17679056 0.98517836]
 [0.34176496 0.9593545 ]
 [0.73446879 0.46681618]
 [0.83385606 0.26364513]]


ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [18]:
def calc_kxb(k1, x1, b1):
    return np.sum(np.dot(k1, x1)) + b1

k = np.array([1, 5, 10])
b = 3
x = np.array([1,2,3])
calc_kxb(k,x,b)

44